#!/bin/sh -X # no runnable script, just for editors
# set -eu is assumed.
# (Note that in ALT /bin/sh is a bash with a few features turned off.)
# (TODO: make sure that ALT's /bin/sh is enough;
# use the lightweight /bin/sh in the actual test scripts.)
#
# At least the syntax in nginxstart() requires bash >= 4 (&>>).

# TESTDIR is usually set in all the testscripts sourcing framework.
. $TESTDIR/framework-without-repo

aptcdrom() { runapt apt-cdrom "${CDROM_OPTS[@]}" "$@"; }

generaterepository() {
	local ORIG_DIR="$1"
	local REPO_DIR="$2"
	local REPO_DATE="${3-}"

	local label="$GB_REPO_LABEL"
	if [ -z "$label" ]; then
		label="apt-tests"
	fi
	local description="$GB_REPO_DESCRIPTION"
	if [ -z "$description" ]; then
		description="ALT Linux $label"
	fi
	local date_s="$(date +%s)"
	local arch="$APT_TEST_USED_ARCH"
	local comps="${label}"

	if [ -n "$REPO_DATE" ] ; then
		date_s="$REPO_DATE"
	fi

	local archive="$GB_REPO_ARCHIVE"
	if [ -z "$archive" ]; then
		archive="$description"
	fi
	local codename="$GB_REPO_CODENAME"
	if [ -z "$codename" ]; then
		codename="$date_s"
	fi
	local origin="$GB_REPO_ORIGIN"
	if [ -z "$origin" ]; then
		origin="ALT Linux Team"
	fi
	local suite="$GB_REPO_SUITE"
	if [ -z "$suite" ]; then
		suite="$label"
	fi
	local version="$GB_REPO_VERSION"
	if [ -z "$version" ]; then
		version="$date_s"
	fi

	# The compression opts can be forced from the environment.
	local compression_opts="$APT_TEST_BASEDIR_COMPRESSION_OPTS"
	if [ -z "$compression_opts" ]; then
		# By default, choose minimal required compressions
		# for the chosen method to work without errors.
		# (FIXME: fix APT so that the used compression doesn't matter!)
		case "$APT_TEST_METHOD" in

			http*) compression_opts='--no-bz2 --xz'
			   ;;

			cdrom*) compression_opts='--bz2 --no-xz'
			   ;;

			*) compression_opts='--no-bz2 --no-xz'
			   ;;

		esac
	fi

	rm -rf "$REPO_DIR"
	for dir in ${arch} noarch ; do
		mkdir -p "${REPO_DIR}/${dir}/RPMS.${label}"
		mkdir -p "${REPO_DIR}/${dir}/base"
		stat "${ORIG_DIR}/${dir}/"*.rpm &>/dev/null &&
			cp "${ORIG_DIR}/${dir}/"*.rpm "${REPO_DIR}/${dir}/RPMS.${label}"/
	done

	mkdir -p "${TMPWORKINGDIRECTORY}/cache"

	for dir in ${arch} noarch ; do
		genbasedir \
			--cachedir="${TMPWORKINGDIRECTORY}/cache" \
			--architecture="$dir" \
			--architectures="$dir" \
			--archive="$archive" \
			--codename="$codename" \
			--description="$description" \
			--label="$label" \
			--origin="$origin" \
			--suite="$suite" \
			--version="$version" \
			--topdir="$REPO_DIR" \
			--changelog-since='@1' \
			--flat --no-oldhashfile $compression_opts --mapi \
			$dir $comps

		if [ -n "$REPO_DATE" ] ; then
			touch -t $(date --date=@${REPO_DATE} '+%Y%m%d%H%M.%S') \
				  "${REPO_DIR}/${dir}/base/"*
		fi
	done
}

generaterepository_and_switch_sources() {
	local -r ORIG_DIR="$1"
	local REPO_DIR # will be set depending on the method
	local -r REPO_DATE="${2-}"

	case "$APT_TEST_METHOD" in

		file)
			REPO_DIR="$TMPWORKINGDIRECTORY/usr/src/RPM/REPO"

			generaterepository "$ORIG_DIR" "$REPO_DIR" "$REPO_DATE"

			# overwrite old sources.list
			cat >| rootdir/etc/apt/sources.list <<- END
				rpm $APT_TEST_METHOD://$REPO_DIR $APT_TEST_USED_ARCH apt-tests
				rpm $APT_TEST_METHOD://$REPO_DIR noarch apt-tests
			END
			;;

		http|https|https_invalid_cert_hostname)
			REPO_DIR="$TMPWORKINGDIRECTORY/nginx/repo"

			generaterepository "$ORIG_DIR" "$REPO_DIR" "$REPO_DATE"

			# overwrite old sources.list
			cat >| rootdir/etc/apt/sources.list <<- END
				rpm ${APT_TEST_METHOD%%_*}://localhost:$((8080+PARALLEL_SLOT))/ $APT_TEST_USED_ARCH apt-tests
				rpm ${APT_TEST_METHOD%%_*}://localhost:$((8080+PARALLEL_SLOT))/ noarch apt-tests
			END
			;;

		cdrom|cdrom_missing_release)

			generaterepository "$ORIG_DIR" "$CDROM_URI" "$REPO_DATE"
			mkdir "$CDROM_URI"/.disk
			# trailing whitespace here might be misinterpreted
			echo "Distribution $REPO_DATE Disk" >"$CDROM_URI"/.disk/info

			# DEBUG: Let's have an idea of the FS tree there:
			#ls -laR "$CDROM_URI"

			case "$APT_TEST_METHOD" in
				cdrom_missing_release)
					find "$CDROM_URI"/*/base -name 'release*' -print -delete
					;;
			esac

			# overwrite old sources.list
			echo >| rootdir/etc/apt/sources.list
			aptcdrom add <<<$'\n'
			;;

		*)
			msgdie 'unknown $APT_TEST_METHOD'
			;;

	esac
}

nginxsetuphttp() {
	mkdir -p $TMPWORKINGDIRECTORY/nginx ||:
	mkdir -p $TMPWORKINGDIRECTORY/nginx/tmp ||:

cat >> $TMPWORKINGDIRECTORY/nginx/nginx.conf << ENDCONFIG
error_log stderr;
worker_processes 1;
pid $TMPWORKINGDIRECTORY/nginx/nginx.pid;

events {
	worker_connections  1024;
}

http {
	client_body_temp_path $TMPWORKINGDIRECTORY/nginx/tmp/client_body;
	fastcgi_temp_path $TMPWORKINGDIRECTORY/nginx/tmp/fastcgi_temp;
	proxy_temp_path $TMPWORKINGDIRECTORY/nginx/tmp/proxy_temp;
	scgi_temp_path $TMPWORKINGDIRECTORY/nginx/tmp/scgi_temp;
	uwsgi_temp_path $TMPWORKINGDIRECTORY/nginx/tmp/uwsgi_temp;

	include             /etc/nginx/mime.types;
	default_type        application/octet-stream;

	sendfile off;

	keepalive_timeout   65;

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_prefer_server_ciphers on;
	access_log stderr;
	error_log stderr;

	server {
		listen $((8080+PARALLEL_SLOT));
		server_name localhost localhost.localdomain;

		location / {
			root $TMPWORKINGDIRECTORY/nginx/repo;
			autoindex on;
		}
	}
}
ENDCONFIG
}

nginxsetuphttps() {
	mkdir -p $TMPWORKINGDIRECTORY/nginx ||:
	mkdir -p $TMPWORKINGDIRECTORY/nginx/tmp ||:

	cat >> $TMPWORKINGDIRECTORY/nginx/nginx.conf << ENDCONFIG
error_log stderr;
worker_processes 1;
pid $TMPWORKINGDIRECTORY/nginx/nginx.pid;

events {
	worker_connections  1024;
}

http {
	client_body_temp_path $TMPWORKINGDIRECTORY/nginx/tmp/client_body;
	fastcgi_temp_path $TMPWORKINGDIRECTORY/nginx/tmp/fastcgi_temp;
	proxy_temp_path $TMPWORKINGDIRECTORY/nginx/tmp/proxy_temp;
	scgi_temp_path $TMPWORKINGDIRECTORY/nginx/tmp/scgi_temp;
	uwsgi_temp_path $TMPWORKINGDIRECTORY/nginx/tmp/uwsgi_temp;

	include             /etc/nginx/mime.types;
	default_type        application/octet-stream;

	sendfile off;

	keepalive_timeout   65;

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_prefer_server_ciphers on;
	access_log stderr;
	error_log stderr;

	server {
		listen $((8080+PARALLEL_SLOT)) ssl;
		server_name localhost localhost.localdomain;

		ssl_certificate	$TMPWORKINGDIRECTORY/nginx/cert.crt;
		ssl_certificate_key	$TMPWORKINGDIRECTORY/nginx/cert.key;

		ssl_session_cache	builtin:1000	shared:SSL:10m;
		ssl_protocols TLSv1.2;
		ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
		ssl_prefer_server_ciphers on;

		location / {
			root $TMPWORKINGDIRECTORY/nginx/repo;
			autoindex on;
		}
	}
}
ENDCONFIG
}

wait_for_file() {
	# The message 'Waiting...' is intentionally printed regardless of $MSGLEVEL;
	# otherwise it would be difficult to see why the process is hanging;
	# it can appear only in extra-ordinary situations (under heavy load).
	[ -s "$1" ] ||
		printf >&2 'Waiting for %s\n' "$1" &&
		while ! [ -s "$1" ]; do
			sleep 0.5
		done
}

nginxstart() {
	local -r NGINXPIDFILE=$TMPWORKINGDIRECTORY/nginx/nginx.pid
	local -r NGINXLOG=$TMPWORKINGDIRECTORY/nginx/process-stderr.log

	# The wait_for_file workaround would not be needed if nginx fully conformed
	# to the "traditional UNIX forking daemon" behavior described
	# in systemd.service(5); unfortunately for us, the upstream hasn't "fixed"
	# this race[1], although a patch for synchronizing the exit of the parent
	# with the creation of the pidfile is available[2].
	# [1]: https://trac.nginx.org/nginx/ticket/1897
	# [2]: http://mailman.nginx.org/pipermail/nginx-ru/2017-November/060628.html
	/usr/sbin/nginx -c $TMPWORKINGDIRECTORY/nginx/nginx.conf -p $TMPWORKINGDIRECTORY &>>"$NGINXLOG" &&
		wait_for_file "$NGINXPIDFILE" &&
		local -r NGINXPID="$(cat "$NGINXPIDFILE" 2>>"$NGINXLOG")" &&
		[ -n "$NGINXPID" ] ||
			{ { echo NGINXLOG:; cat "$NGINXLOG"; } >&2 ||:
			  msgdie 'nginx failed to start normally'
			}

	addtrap 'prefix' \
			'kill -TERM %q ||:; [ "$EXIT_CODE" = 0 ] || if [ -e %q ]; then echo NGINXLOG:; cat %q ||:; fi;' \
			"$NGINXPID" \
			"$NGINXLOG"
}
