#!/bin/bash
set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment

buildpackage "simple-package"
testpkgnotinstalled "simple-package"
aptgetinstallpackage "simple-package" "1" "alt1" "$(getarchitecture)"
msgmsg "Installed package \"simple-package\""
testpkginstalled "simple-package"
testsuccess aptget -y remove "simple-package"
testpkgnotinstalled "simple-package"
