#!/bin/bash
set -eu

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment

buildpackage 'simple-package'
readonly P=simple-package-update
readonly N=$(( 3 * 1024 ))
F="$(mktemp "${TESTDIRECTORY}/specs/$P-XXXX.spec")"
F="${F%.spec}"
readonly F
addtrap 'rm -f %q.{spec,metainfo}' "$F"
for (( i=2; i <= N; ++i )); do
    sed -E \
	-e 's/^Version:[[:space:]]* 2$/'"Version: $i/" \
	-e 's/ 2-alt1$/'" $i-alt1/" \
	<"${TESTDIRECTORY}/specs/$P.spec" \
	>|"$F.spec"
    sed -E \
	-e 's/version=2$/'"version=$i/" \
	<"${TESTDIRECTORY}/specs/$P.metainfo" \
	>|"$F.metainfo"
    buildpackage "${F##*/}"
done
buildpackage 'conflicting-package-one'
buildpackage 'conflicting-package-distupgrade'

testpkgnotinstalled 'simple-package'
testpkgnotinstalled 'conflicting-package-one'
aptgetinstallpackage 'simple-package'
aptgetinstallpackage 'conflicting-package-one'
testpkginstalled 'simple-package'
testpkginstalled 'conflicting-package-one'

testequal '1-alt1' getpackageversion 'simple-package'
testequal '1-alt1' getpackageversion 'conflicting-package-one'

generaterepository_and_switch_sources "$TMPWORKINGDIRECTORY/usr/src/RPM/RPMS"

testsuccess aptget update

# At least, it fails on assertion instead of badly overflowing the buffer.
testregexmatch '.*: Assertion .* failed\.' aptget dist-upgrade -y
testfailure

# More correct behavior would be:
#testsuccess aptget dist-upgrade -y
#testequal "$N-alt1" getpackageversion 'simple-package'
#testequal '1-alt1' getpackageversion 'conflicting-package-one'
