#!/bin/bash
set -eu

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment

buildpackage 'simple-package'
testpkgnotinstalled 'simple-package'
aptgetinstallpackage 'simple-package'
msgmsg 'Installed package "simple-package"'
testpkginstalled 'simple-package'
testsuccess aptget -y remove 'simple-package'
testpkgnotinstalled 'simple-package'
