#!/bin/bash
set -eu

TESTDIR=$(readlink -f $(dirname $0))

case "$APT_TEST_METHOD" in
	https*)
		:
		;;
	*)
		echo 'SKIP (makes sense only for APT_TEST_METHOD being https*)' >&2
		exit 0
		;;
esac

. $TESTDIR/framework-without-repo
prereq $TESTDIR/test-apt-install-simple

# generate another key, and pin apt to it. Check key pinning
msgmsg 'Pinning invalid key in apt'
openssl req -x509 -newkey rsa:4096 -keyout $TMPWORKINGDIRECTORY/nginx/cert.invalid.key -out $TMPWORKINGDIRECTORY/nginx/cert.invalid.crt -nodes -days 365 -subj '/CN=localhost' &>/dev/null

cat > $TMPWORKINGDIRECTORY/rootdir/etc/apt/apt.conf.d/81https-pinning.conf << END
Acquire::https::PinnedCert	"$TMPWORKINGDIRECTORY/nginx/cert.invalid.crt";
END

testfailure aptget update

testpkgnotinstalled 'conflicting-package-one'
testfailure aptget install conflicting-package-one
testpkgnotinstalled 'conflicting-package-one'
