#!/bin/bash
set -eu

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment

buildpackage 'simple-package'

testpkgnotinstalled 'simple-package'
aptgetinstallpackage 'simple-package'
testpkginstalled 'simple-package'
