#!/bin/bash
set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment

buildpackage "conflicting-package-distupgrade"
buildpackage "conflicting-package-one"
buildpackage "conflicting-package-two"
buildpackage "missing-dependency"
buildpackage "simple-package-new"
buildpackage "simple-package-noarch"
buildpackage "simple-package"
buildpackage "simple-package-update-conflict"
buildpackage "simple-package-update"
buildpackage "simple-virtual"

generaterepository "$TMPWORKINGDIRECTORY/usr/src/RPM/RPMS" "$TMPWORKINGDIRECTORY/usr/src/RPM/REPO"

testsuccess aptget update

testequal "conflicting-package-two
no-such-package
simple-virtual
simple-package-noarch
virtual(dummy)
simple-package-new
missing-dependency
simple-package
conflicting-package-one" aptcache pkgnames
