#!/bin/bash
set -eu

TESTDIR=$(readlink -f $(dirname $0))

if [ -z "${APT_TEST_GPGPUBKEY}" ]; then
	echo 'SKIP (requires the presence of APT_TEST_GPGPUBKEY)' >&2
	exit 0
fi

. $TESTDIR/framework-without-repo

setupenvironment

testpkginstalled 'gpg-pubkey'
testsuccess aptget -y remove 'gpg-pubkey'
testpkgnotinstalled 'gpg-pubkey'
