#!/bin/bash
set -eu

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment

buildpackage 'conflicting-package-distupgrade'
buildpackage 'conflicting-package-one'
buildpackage 'conflicting-package-two'
buildpackage 'missing-dependency'
buildpackage 'simple-package-new'
buildpackage 'simple-package-noarch'
buildpackage 'simple-package'
buildpackage 'simple-package-update-conflict'
buildpackage 'simple-package-update' # overwrites the previous built package

generaterepository_and_switch_sources "$TMPWORKINGDIRECTORY/usr/src/RPM/RPMS"

testsuccess aptget update

if [ -n "$APT_TEST_GPGPUBKEY" ]; then
	dump_with_gpgpubkey=(
		'Package: gpg\([^)]*@[^)]*\)'

		'Package: gpg\([^)]*\)'

		# $'' is used for \n
		$'Package: gpg-pubkey
 Version: [^-]*-[^-]*@[0-9]+
     File: /[^\n]*/var/lib/rpm/Packages'

	)
else
	dump_with_gpgpubkey=()
fi
readonly -a dump_with_gpgpubkey

testpartsexhaust "${dump_with_gpgpubkey[@]}" \
'Using Versioning System: Standard \.rpm
Package: conflicting-package-two
 Version: 1-alt1@[0-9]+
     File: /.*/rootdir/var/lib/apt/lists/.*_usr_src_RPM_REPO_.*_base_pkglist\.apt-tests
  Depends: conflicting-package-one \(null\)
Package: no-such-package
Package: simple-package-noarch
 Version: 1-alt1@[0-9]+
     File: /.*/rootdir/var/lib/apt/lists/.*_usr_src_RPM_REPO_noarch_base_pkglist\.apt-tests
Package: simple-package-new
 Version: 3-alt1@[0-9]+
     File: /.*/rootdir/var/lib/apt/lists/.*_usr_src_RPM_REPO_.*_base_pkglist\.apt-tests
  Depends: simple-package 3-alt1
  Depends: simple-package 3-alt1
Package: missing-dependency
 Version: 1-alt1@[0-9]+
     File: /.*/rootdir/var/lib/apt/lists/.*_usr_src_RPM_REPO_.*_base_pkglist\.apt-tests
  Depends: no-such-package \(null\)
Package: simple-package
 Version: 2-alt1@[0-9]+
     File: /.*/rootdir/var/lib/apt/lists/.*_usr_src_RPM_REPO_.*_base_pkglist\.apt-tests
 Version: 1-alt1@[0-9]+
     File: /.*/rootdir/var/lib/apt/lists/.*_usr_src_RPM_REPO_.*_base_pkglist\.apt-tests
Package: conflicting-package-one
 Version: 2-alt1@[0-9]+
     File: /.*/rootdir/var/lib/apt/lists/.*_usr_src_RPM_REPO_.*_base_pkglist\.apt-tests
  Depends: conflicting-package-two \(null\)
  Depends: simple-package \(null\)
 Version: 1-alt1@[0-9]+
     File: /.*/rootdir/var/lib/apt/lists/.*_usr_src_RPM_REPO_.*_base_pkglist\.apt-tests
  Depends: conflicting-package-two \(null\)
File: /.*/var/lib/rpm/Packages
 Type: RPM Database
 Size: [0-9]+
 ID: 2
 Flags: 1
 Time: .*
 Archive: \(null\)
 Component: \(null\)
 Version: \(null\)
 Origin: \(null\)
 Site:[ ]*
 Label: \(null\)
 Architecture: \(null\)
File: /.*/rootdir/var/lib/apt/lists/.*_usr_src_RPM_REPO_noarch_base_pkglist\.apt-tests
 Type: RPM Package Index
 Size: [0-9]+
 ID: 1
 Flags: 0
 Time: .*
 Archive: ALT Linux apt-tests
 Component: apt-tests
 Version: [0-9]+
 Origin: ALT Linux Team
 Site:[ ]*
 Label: apt-tests
 Architecture: noarch
File: /.*/rootdir/var/lib/apt/lists/.*_usr_src_RPM_REPO_.*_base_pkglist\.apt-tests
 Type: RPM Package Index
 Size: [0-9]+
 ID: 0
 Flags: 0
 Time: .*
 Archive: ALT Linux apt-tests
 Component: apt-tests
 Version: [0-9]+
 Origin: ALT Linux Team
 Site:[ ]*
 Label: apt-tests'"
 Architecture: $APT_TEST_USED_ARCH" \
-- aptcache dump
