#!/bin/bash
set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment

buildpackage 'simple-package'
buildpackage 'simple-package-update'
buildpackage 'conflicting-package-one'
buildpackage 'conflicting-package-distupgrade'

testpkgnotinstalled 'simple-package'
testpkgnotinstalled 'conflicting-package-one'
aptgetinstallpackage 'simple-package' '1' 'alt1' "$(getarchitecture)"
aptgetinstallpackage 'conflicting-package-one' '1' 'alt1' "$(getarchitecture)"
testpkginstalled 'simple-package'
testpkginstalled 'conflicting-package-one'

testequal '1-alt1' getpackageversion 'simple-package'
testequal '1-alt1' getpackageversion 'conflicting-package-one'

generaterepository "$TMPWORKINGDIRECTORY/usr/src/RPM/RPMS" "$TMPWORKINGDIRECTORY/usr/src/RPM/REPO"

testsuccess aptget update

testsuccess aptget dist-upgrade -y
testequal '2-alt1' getpackageversion 'simple-package'
testequal '1-alt1' getpackageversion 'conflicting-package-one'
