#!/bin/bash
set -eu

# for peculiarities MarkInstallRec()

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment

buildpackage 'simple-package' # version: 1
buildpackage 'simple-package-update' # version: 2
buildpackage 'conflicts-simple-package-less-2'

testpkgnotinstalled 'simple-package'
aptgetinstallpackage 'simple-package-update'
testpkginstalled 'simple-package'

testequal '2-alt1' getpackageversion 'simple-package'

generaterepository_and_switch_sources "$TMPWORKINGDIRECTORY/usr/src/RPM/RPMS"

testsuccess aptget update

testpkgnotinstalled 'conflicts-simple-package-less-2'
testsuccess aptget \
	    -o Debug::pkgMarkInstall=yes \
	    -o Debug::pkgMarkAllCalls=yes \
	    install -y conflicts-simple-package-less-2
testpkginstalled 'conflicts-simple-package-less-2'

testpkginstalled 'simple-package'
