#!/bin/bash
set -eu

TESTDIR=$(readlink -f $(dirname $0))

case "$APT_TEST_METHOD" in
	cdrom*)
		echo 'SKIP (not ready for apt-cdrom, because it fetches the lists earlier)' >&2
		exit 0
		;;
esac

. $TESTDIR/test-apt-update-simple

case "$APT_TEST_METHOD" in
	file*) APT_TEST_XFAIL=yes
	       ;;
esac

# Fake pkglist (only noarch, since a noarch pkg is definitely present).
#
# It's simpler to edit the release file -- see the comments in
# test-apt-update-verifies-cksum-of-pkglist-index.

BAD_CKSUM="$(md5sum /dev/null | cut -d' ' -f1)"
readonly BAD_CKSUM
readonly REPO_NOARCH_RELEASE="$REPO_STORAGE/$NOARCH_DISTRO/base/release"
mv "$REPO_NOARCH_RELEASE"{,.orig}
sed -Ee "/^MD5Sum:/,\$ { /pkglist/ s:^ [^ ]* : $BAD_CKSUM :; }" \
    >"$REPO_NOARCH_RELEASE" \
    <"$REPO_NOARCH_RELEASE".orig
touch -r "$REPO_NOARCH_RELEASE".orig -- "$REPO_NOARCH_RELEASE"
rm -- "$REPO_NOARCH_RELEASE".orig

# Cksum verification shouldn't pass.
# apt should discard the old fetched pkglist, shouldn't it?
# Because now it sees a new release file with a different cksum.

testregexmatch '.*MD5Sum mismatch.*' aptget update
testfailure
testsuccess aptcache show simple-package
testfailure aptcache show simple-package-noarch
testfailure aptcache show nosuchpkg
