#!/bin/bash
set -eu

# a single test overriding the method
APT_TEST_METHOD=http

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment

nginxsetuphttp

buildpackage 'simple-package'

generaterepository_and_switch_sources "$TMPWORKINGDIRECTORY/usr/src/RPM/RPMS"

nginxstart

testsuccess aptget \
	    -o Acquire::Verbose=yes \
	    -o Debug::pkgAcquire::Auth=yes \
	    update

testpkgnotinstalled 'simple-package'
testsuccess aptget install simple-package
testpkginstalled 'simple-package'
