#!/bin/bash
set -eu

TESTDIR=$(readlink -f $(dirname $0))

# In ALT, only BLAKE2b and MD5 cksums are considered.
export APT_TEST_XFAIL=yes

# apt-repo-tools (post 0.8.0 sha2 branch) implements it, but needs an option.
export APT_TEST_GENBASEDIR_OPTS="${APT_TEST_GENBASEDIR_OPTS} --sha1"

exec $TESTDIR/tmpl-apt-install-verifies-CKSUM-of-rpm-archive.sh 'SHA1'
